// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: topup.proto

package topuppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupRequest) Reset() {
	*x = TopupRequest{}
	mi := &file_topup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupRequest) ProtoMessage() {}

func (x *TopupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupRequest.ProtoReflect.Descriptor instead.
func (*TopupRequest) Descriptor() ([]byte, []int) {
	return file_topup_proto_rawDescGZIP(), []int{0}
}

func (x *TopupRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *TopupRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TopupRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type TopupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopupResponse) Reset() {
	*x = TopupResponse{}
	mi := &file_topup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopupResponse) ProtoMessage() {}

func (x *TopupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopupResponse.ProtoReflect.Descriptor instead.
func (*TopupResponse) Descriptor() ([]byte, []int) {
	return file_topup_proto_rawDescGZIP(), []int{1}
}

func (x *TopupResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TopupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_topup_proto protoreflect.FileDescriptor

const file_topup_proto_rawDesc = "" +
	"\n" +
	"\vtopup.proto\x12\x10wholesales.topup\"]\n" +
	"\fTopupRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x03R\tcompanyId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\"9\n" +
	"\rTopupResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2X\n" +
	"\fTopupService\x12H\n" +
	"\x05Topup\x12\x1e.wholesales.topup.TopupRequest\x1a\x1f.wholesales.topup.TopupResponseBGZEgithub.com/RizkyHertama/wholesales-app/backend/internal/topup;topuppbb\x06proto3"

var (
	file_topup_proto_rawDescOnce sync.Once
	file_topup_proto_rawDescData []byte
)

func file_topup_proto_rawDescGZIP() []byte {
	file_topup_proto_rawDescOnce.Do(func() {
		file_topup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topup_proto_rawDesc), len(file_topup_proto_rawDesc)))
	})
	return file_topup_proto_rawDescData
}

var file_topup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_topup_proto_goTypes = []any{
	(*TopupRequest)(nil),  // 0: wholesales.topup.TopupRequest
	(*TopupResponse)(nil), // 1: wholesales.topup.TopupResponse
}
var file_topup_proto_depIdxs = []int32{
	0, // 0: wholesales.topup.TopupService.Topup:input_type -> wholesales.topup.TopupRequest
	1, // 1: wholesales.topup.TopupService.Topup:output_type -> wholesales.topup.TopupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_topup_proto_init() }
func file_topup_proto_init() {
	if File_topup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topup_proto_rawDesc), len(file_topup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topup_proto_goTypes,
		DependencyIndexes: file_topup_proto_depIdxs,
		MessageInfos:      file_topup_proto_msgTypes,
	}.Build()
	File_topup_proto = out.File
	file_topup_proto_goTypes = nil
	file_topup_proto_depIdxs = nil
}
