-- 001_init.sql (Postgres version)

\connect wholesales_db

CREATE TABLE companies (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  bank_code VARCHAR(20) NOT NULL,
  account_number VARCHAR(100) NOT NULL UNIQUE,
  balance NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admins (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  role VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transfers (
  id BIGSERIAL PRIMARY KEY,
  trace_id VARCHAR(128) NOT NULL UNIQUE,
  from_company_id BIGINT NOT NULL REFERENCES companies(id),
  to_company_id BIGINT REFERENCES companies(id),
  to_bank_code VARCHAR(20) NOT NULL,
  to_account_number VARCHAR(100) NOT NULL,
  amount NUMERIC(18,2) NOT NULL,
  method VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  fee NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMP NULL
);

CREATE TABLE topups (
  id BIGSERIAL PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id),
  amount NUMERIC(18,2) NOT NULL,
  method VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
