// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: transfer.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferType int32

const (
	TransferType_INTERNAL TransferType = 0
	TransferType_EXTERNAL TransferType = 1
)

// Enum value maps for TransferType.
var (
	TransferType_name = map[int32]string{
		0: "INTERNAL",
		1: "EXTERNAL",
	}
	TransferType_value = map[string]int32{
		"INTERNAL": 0,
		"EXTERNAL": 1,
	}
)

func (x TransferType) Enum() *TransferType {
	p := new(TransferType)
	*p = x
	return p
}

func (x TransferType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferType) Descriptor() protoreflect.EnumDescriptor {
	return file_transfer_proto_enumTypes[0].Descriptor()
}

func (TransferType) Type() protoreflect.EnumType {
	return &file_transfer_proto_enumTypes[0]
}

func (x TransferType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferType.Descriptor instead.
func (TransferType) EnumDescriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_BI_FAST PaymentMethod = 0
	PaymentMethod_RTGS    PaymentMethod = 1
	PaymentMethod_SKN     PaymentMethod = 2
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "BI_FAST",
		1: "RTGS",
		2: "SKN",
	}
	PaymentMethod_value = map[string]int32{
		"BI_FAST": 0,
		"RTGS":    1,
		"SKN":     2,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_transfer_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_transfer_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{1}
}

type Transfer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromCompanyId   int64                  `protobuf:"varint,2,opt,name=from_company_id,json=fromCompanyId,proto3" json:"from_company_id,omitempty"`
	ToCompanyId     int64                  `protobuf:"varint,3,opt,name=to_company_id,json=toCompanyId,proto3" json:"to_company_id,omitempty"`
	ToAccountNumber string                 `protobuf:"bytes,4,opt,name=to_account_number,json=toAccountNumber,proto3" json:"to_account_number,omitempty"`
	ToBankName      string                 `protobuf:"bytes,5,opt,name=to_bank_name,json=toBankName,proto3" json:"to_bank_name,omitempty"`
	Amount          float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee             float64                `protobuf:"fixed64,7,opt,name=fee,proto3" json:"fee,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,8,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TransferType    string                 `protobuf:"bytes,9,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Note            string                 `protobuf:"bytes,11,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transfer) GetFromCompanyId() int64 {
	if x != nil {
		return x.FromCompanyId
	}
	return 0
}

func (x *Transfer) GetToCompanyId() int64 {
	if x != nil {
		return x.ToCompanyId
	}
	return 0
}

func (x *Transfer) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *Transfer) GetToBankName() string {
	if x != nil {
		return x.ToBankName
	}
	return ""
}

func (x *Transfer) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transfer) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Transfer) GetTransferType() string {
	if x != nil {
		return x.TransferType
	}
	return ""
}

func (x *Transfer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transfer) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Transfer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DoTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromCompanyId   int64                  `protobuf:"varint,1,opt,name=from_company_id,json=fromCompanyId,proto3" json:"from_company_id,omitempty"`
	ToAccountNumber string                 `protobuf:"bytes,2,opt,name=to_account_number,json=toAccountNumber,proto3" json:"to_account_number,omitempty"`
	ToBankName      string                 `protobuf:"bytes,3,opt,name=to_bank_name,json=toBankName,proto3" json:"to_bank_name,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	TransferType    TransferType           `protobuf:"varint,5,opt,name=transfer_type,json=transferType,proto3,enum=transfer.TransferType" json:"transfer_type,omitempty"`
	PaymentMethod   PaymentMethod          `protobuf:"varint,6,opt,name=payment_method,json=paymentMethod,proto3,enum=transfer.PaymentMethod" json:"payment_method,omitempty"`
	Note            string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DoTransferRequest) Reset() {
	*x = DoTransferRequest{}
	mi := &file_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoTransferRequest) ProtoMessage() {}

func (x *DoTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoTransferRequest.ProtoReflect.Descriptor instead.
func (*DoTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *DoTransferRequest) GetFromCompanyId() int64 {
	if x != nil {
		return x.FromCompanyId
	}
	return 0
}

func (x *DoTransferRequest) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *DoTransferRequest) GetToBankName() string {
	if x != nil {
		return x.ToBankName
	}
	return ""
}

func (x *DoTransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DoTransferRequest) GetTransferType() TransferType {
	if x != nil {
		return x.TransferType
	}
	return TransferType_INTERNAL
}

func (x *DoTransferRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_BI_FAST
}

func (x *DoTransferRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type DoTransferResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Message          string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	RemainingBalance float64                `protobuf:"fixed64,3,opt,name=remaining_balance,json=remainingBalance,proto3" json:"remaining_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DoTransferResponse) Reset() {
	*x = DoTransferResponse{}
	mi := &file_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoTransferResponse) ProtoMessage() {}

func (x *DoTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoTransferResponse.ProtoReflect.Descriptor instead.
func (*DoTransferResponse) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *DoTransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DoTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DoTransferResponse) GetRemainingBalance() float64 {
	if x != nil {
		return x.RemainingBalance
	}
	return 0
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     int64                  `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *GetHistoryRequest) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *GetHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

func (x *GetHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_transfer_proto protoreflect.FileDescriptor

const file_transfer_proto_rawDesc = "" +
	"\n" +
	"\x0etransfer.proto\x12\btransfer\"\xf5\x02\n" +
	"\bTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0ffrom_company_id\x18\x02 \x01(\x03R\rfromCompanyId\x12\"\n" +
	"\rto_company_id\x18\x03 \x01(\x03R\vtoCompanyId\x12*\n" +
	"\x11to_account_number\x18\x04 \x01(\tR\x0ftoAccountNumber\x12 \n" +
	"\fto_bank_name\x18\x05 \x01(\tR\n" +
	"toBankName\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x10\n" +
	"\x03fee\x18\a \x01(\x01R\x03fee\x12%\n" +
	"\x0epayment_method\x18\b \x01(\tR\rpaymentMethod\x12#\n" +
	"\rtransfer_type\x18\t \x01(\tR\ftransferType\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\v \x01(\tR\x04note\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\xb2\x02\n" +
	"\x11DoTransferRequest\x12&\n" +
	"\x0ffrom_company_id\x18\x01 \x01(\x03R\rfromCompanyId\x12*\n" +
	"\x11to_account_number\x18\x02 \x01(\tR\x0ftoAccountNumber\x12 \n" +
	"\fto_bank_name\x18\x03 \x01(\tR\n" +
	"toBankName\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12;\n" +
	"\rtransfer_type\x18\x05 \x01(\x0e2\x16.transfer.TransferTypeR\ftransferType\x12>\n" +
	"\x0epayment_method\x18\x06 \x01(\x0e2\x17.transfer.PaymentMethodR\rpaymentMethod\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\"u\n" +
	"\x12DoTransferResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12+\n" +
	"\x11remaining_balance\x18\x03 \x01(\x01R\x10remainingBalance\"\\\n" +
	"\x11GetHistoryRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\x03R\tcompanyId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\\\n" +
	"\x12GetHistoryResponse\x120\n" +
	"\ttransfers\x18\x01 \x03(\v2\x12.transfer.TransferR\ttransfers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total**\n" +
	"\fTransferType\x12\f\n" +
	"\bINTERNAL\x10\x00\x12\f\n" +
	"\bEXTERNAL\x10\x01*/\n" +
	"\rPaymentMethod\x12\v\n" +
	"\aBI_FAST\x10\x00\x12\b\n" +
	"\x04RTGS\x10\x01\x12\a\n" +
	"\x03SKN\x10\x022\xa3\x01\n" +
	"\x0fTransferService\x12G\n" +
	"\n" +
	"DoTransfer\x12\x1b.transfer.DoTransferRequest\x1a\x1c.transfer.DoTransferResponse\x12G\n" +
	"\n" +
	"GetHistory\x12\x1b.transfer.GetHistoryRequest\x1a\x1c.transfer.GetHistoryResponseB\"Z wholesales-app/backend/server/pbb\x06proto3"

var (
	file_transfer_proto_rawDescOnce sync.Once
	file_transfer_proto_rawDescData []byte
)

func file_transfer_proto_rawDescGZIP() []byte {
	file_transfer_proto_rawDescOnce.Do(func() {
		file_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_proto_rawDesc), len(file_transfer_proto_rawDesc)))
	})
	return file_transfer_proto_rawDescData
}

var file_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_transfer_proto_goTypes = []any{
	(TransferType)(0),          // 0: transfer.TransferType
	(PaymentMethod)(0),         // 1: transfer.PaymentMethod
	(*Transfer)(nil),           // 2: transfer.Transfer
	(*DoTransferRequest)(nil),  // 3: transfer.DoTransferRequest
	(*DoTransferResponse)(nil), // 4: transfer.DoTransferResponse
	(*GetHistoryRequest)(nil),  // 5: transfer.GetHistoryRequest
	(*GetHistoryResponse)(nil), // 6: transfer.GetHistoryResponse
}
var file_transfer_proto_depIdxs = []int32{
	0, // 0: transfer.DoTransferRequest.transfer_type:type_name -> transfer.TransferType
	1, // 1: transfer.DoTransferRequest.payment_method:type_name -> transfer.PaymentMethod
	2, // 2: transfer.GetHistoryResponse.transfers:type_name -> transfer.Transfer
	3, // 3: transfer.TransferService.DoTransfer:input_type -> transfer.DoTransferRequest
	5, // 4: transfer.TransferService.GetHistory:input_type -> transfer.GetHistoryRequest
	4, // 5: transfer.TransferService.DoTransfer:output_type -> transfer.DoTransferResponse
	6, // 6: transfer.TransferService.GetHistory:output_type -> transfer.GetHistoryResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_transfer_proto_init() }
func file_transfer_proto_init() {
	if File_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_proto_rawDesc), len(file_transfer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfer_proto_goTypes,
		DependencyIndexes: file_transfer_proto_depIdxs,
		EnumInfos:         file_transfer_proto_enumTypes,
		MessageInfos:      file_transfer_proto_msgTypes,
	}.Build()
	File_transfer_proto = out.File
	file_transfer_proto_goTypes = nil
	file_transfer_proto_depIdxs = nil
}
