// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: transfer.proto

package transferpb

import (
	common "github.com/RizkyHertama/wholesales-app/backend/internal/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransferRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	FromCompanyId   int64                  `protobuf:"varint,2,opt,name=from_company_id,json=fromCompanyId,proto3" json:"from_company_id,omitempty"`
	ToBankCode      string                 `protobuf:"bytes,3,opt,name=to_bank_code,json=toBankCode,proto3" json:"to_bank_code,omitempty"`
	ToAccountNumber string                 `protobuf:"bytes,4,opt,name=to_account_number,json=toAccountNumber,proto3" json:"to_account_number,omitempty"`
	Amount          float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Method          common.TransferMethod  `protobuf:"varint,6,opt,name=method,proto3,enum=wholesales.common.TransferMethod" json:"method,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransferRequest) Reset() {
	*x = CreateTransferRequest{}
	mi := &file_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferRequest) ProtoMessage() {}

func (x *CreateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferRequest.ProtoReflect.Descriptor instead.
func (*CreateTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransferRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateTransferRequest) GetFromCompanyId() int64 {
	if x != nil {
		return x.FromCompanyId
	}
	return 0
}

func (x *CreateTransferRequest) GetToBankCode() string {
	if x != nil {
		return x.ToBankCode
	}
	return ""
}

func (x *CreateTransferRequest) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *CreateTransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransferRequest) GetMethod() common.TransferMethod {
	if x != nil {
		return x.Method
	}
	return common.TransferMethod(0)
}

type CreateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Status        common.TransferStatus  `protobuf:"varint,2,opt,name=status,proto3,enum=wholesales.common.TransferStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransferResponse) Reset() {
	*x = CreateTransferResponse{}
	mi := &file_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransferResponse) ProtoMessage() {}

func (x *CreateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransferResponse.ProtoReflect.Descriptor instead.
func (*CreateTransferResponse) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransferResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateTransferResponse) GetStatus() common.TransferStatus {
	if x != nil {
		return x.Status
	}
	return common.TransferStatus(0)
}

func (x *CreateTransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferRequest) Reset() {
	*x = GetTransferRequest{}
	mi := &file_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferRequest) ProtoMessage() {}

func (x *GetTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferRequest.ProtoReflect.Descriptor instead.
func (*GetTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransferRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type TransferRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TraceId         string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	FromCompanyId   int64                  `protobuf:"varint,3,opt,name=from_company_id,json=fromCompanyId,proto3" json:"from_company_id,omitempty"`
	ToCompanyId     int64                  `protobuf:"varint,4,opt,name=to_company_id,json=toCompanyId,proto3" json:"to_company_id,omitempty"`
	ToBankCode      string                 `protobuf:"bytes,5,opt,name=to_bank_code,json=toBankCode,proto3" json:"to_bank_code,omitempty"`
	ToAccountNumber string                 `protobuf:"bytes,6,opt,name=to_account_number,json=toAccountNumber,proto3" json:"to_account_number,omitempty"`
	Amount          float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Method          common.TransferMethod  `protobuf:"varint,8,opt,name=method,proto3,enum=wholesales.common.TransferMethod" json:"method,omitempty"`
	Status          common.TransferStatus  `protobuf:"varint,9,opt,name=status,proto3,enum=wholesales.common.TransferStatus" json:"status,omitempty"`
	Fee             float64                `protobuf:"fixed64,10,opt,name=fee,proto3" json:"fee,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ProcessedAt     string                 `protobuf:"bytes,12,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferRecord) Reset() {
	*x = TransferRecord{}
	mi := &file_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRecord) ProtoMessage() {}

func (x *TransferRecord) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRecord.ProtoReflect.Descriptor instead.
func (*TransferRecord) Descriptor() ([]byte, []int) {
	return file_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *TransferRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TransferRecord) GetFromCompanyId() int64 {
	if x != nil {
		return x.FromCompanyId
	}
	return 0
}

func (x *TransferRecord) GetToCompanyId() int64 {
	if x != nil {
		return x.ToCompanyId
	}
	return 0
}

func (x *TransferRecord) GetToBankCode() string {
	if x != nil {
		return x.ToBankCode
	}
	return ""
}

func (x *TransferRecord) GetToAccountNumber() string {
	if x != nil {
		return x.ToAccountNumber
	}
	return ""
}

func (x *TransferRecord) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRecord) GetMethod() common.TransferMethod {
	if x != nil {
		return x.Method
	}
	return common.TransferMethod(0)
}

func (x *TransferRecord) GetStatus() common.TransferStatus {
	if x != nil {
		return x.Status
	}
	return common.TransferStatus(0)
}

func (x *TransferRecord) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransferRecord) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransferRecord) GetProcessedAt() string {
	if x != nil {
		return x.ProcessedAt
	}
	return ""
}

var File_transfer_proto protoreflect.FileDescriptor

const file_transfer_proto_rawDesc = "" +
	"\n" +
	"\x0etransfer.proto\x12\x13wholesales.transfer\x1a\fcommon.proto\"\xfb\x01\n" +
	"\x15CreateTransferRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12&\n" +
	"\x0ffrom_company_id\x18\x02 \x01(\x03R\rfromCompanyId\x12 \n" +
	"\fto_bank_code\x18\x03 \x01(\tR\n" +
	"toBankCode\x12*\n" +
	"\x11to_account_number\x18\x04 \x01(\tR\x0ftoAccountNumber\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x129\n" +
	"\x06method\x18\x06 \x01(\x0e2!.wholesales.common.TransferMethodR\x06method\"\x88\x01\n" +
	"\x16CreateTransferResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.wholesales.common.TransferStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"/\n" +
	"\x12GetTransferRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"\xb7\x03\n" +
	"\x0eTransferRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12&\n" +
	"\x0ffrom_company_id\x18\x03 \x01(\x03R\rfromCompanyId\x12\"\n" +
	"\rto_company_id\x18\x04 \x01(\x03R\vtoCompanyId\x12 \n" +
	"\fto_bank_code\x18\x05 \x01(\tR\n" +
	"toBankCode\x12*\n" +
	"\x11to_account_number\x18\x06 \x01(\tR\x0ftoAccountNumber\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x129\n" +
	"\x06method\x18\b \x01(\x0e2!.wholesales.common.TransferMethodR\x06method\x129\n" +
	"\x06status\x18\t \x01(\x0e2!.wholesales.common.TransferStatusR\x06status\x12\x10\n" +
	"\x03fee\x18\n" +
	" \x01(\x01R\x03fee\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12!\n" +
	"\fprocessed_at\x18\f \x01(\tR\vprocessedAt2\xd9\x01\n" +
	"\x0fTransferService\x12i\n" +
	"\x0eCreateTransfer\x12*.wholesales.transfer.CreateTransferRequest\x1a+.wholesales.transfer.CreateTransferResponse\x12[\n" +
	"\vGetTransfer\x12'.wholesales.transfer.GetTransferRequest\x1a#.wholesales.transfer.TransferRecordBMZKgithub.com/RizkyHertama/wholesales-app/backend/internal/transfer;transferpbb\x06proto3"

var (
	file_transfer_proto_rawDescOnce sync.Once
	file_transfer_proto_rawDescData []byte
)

func file_transfer_proto_rawDescGZIP() []byte {
	file_transfer_proto_rawDescOnce.Do(func() {
		file_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_proto_rawDesc), len(file_transfer_proto_rawDesc)))
	})
	return file_transfer_proto_rawDescData
}

var file_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transfer_proto_goTypes = []any{
	(*CreateTransferRequest)(nil),  // 0: wholesales.transfer.CreateTransferRequest
	(*CreateTransferResponse)(nil), // 1: wholesales.transfer.CreateTransferResponse
	(*GetTransferRequest)(nil),     // 2: wholesales.transfer.GetTransferRequest
	(*TransferRecord)(nil),         // 3: wholesales.transfer.TransferRecord
	(common.TransferMethod)(0),     // 4: wholesales.common.TransferMethod
	(common.TransferStatus)(0),     // 5: wholesales.common.TransferStatus
}
var file_transfer_proto_depIdxs = []int32{
	4, // 0: wholesales.transfer.CreateTransferRequest.method:type_name -> wholesales.common.TransferMethod
	5, // 1: wholesales.transfer.CreateTransferResponse.status:type_name -> wholesales.common.TransferStatus
	4, // 2: wholesales.transfer.TransferRecord.method:type_name -> wholesales.common.TransferMethod
	5, // 3: wholesales.transfer.TransferRecord.status:type_name -> wholesales.common.TransferStatus
	0, // 4: wholesales.transfer.TransferService.CreateTransfer:input_type -> wholesales.transfer.CreateTransferRequest
	2, // 5: wholesales.transfer.TransferService.GetTransfer:input_type -> wholesales.transfer.GetTransferRequest
	1, // 6: wholesales.transfer.TransferService.CreateTransfer:output_type -> wholesales.transfer.CreateTransferResponse
	3, // 7: wholesales.transfer.TransferService.GetTransfer:output_type -> wholesales.transfer.TransferRecord
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_transfer_proto_init() }
func file_transfer_proto_init() {
	if File_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_proto_rawDesc), len(file_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfer_proto_goTypes,
		DependencyIndexes: file_transfer_proto_depIdxs,
		MessageInfos:      file_transfer_proto_msgTypes,
	}.Build()
	File_transfer_proto = out.File
	file_transfer_proto_goTypes = nil
	file_transfer_proto_depIdxs = nil
}
